version: '3'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"] 
      timeout: 10s
      retries: 5

  backend:
    container_name: app_backend
    build: ./backend
    restart: always
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: dev
    volumes: 
      - ./backend/src:/app-backend/src
    depends_on:
      - db
    environment:
      - APP_PORT=3001           
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=todo_db
      - DB_PORT=3306  
  db:
    container_name: todo_db
    image: mysql:latest
    restart: always
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
