version: '3'
services:        
  db:
    container_name: todo_db
    image: mysql:latest
    restart: always
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      HOST: todo_db
      PORT: 3001
    ports:
      - 3306:3306
